[tool.poetry]
name = "fixm4b"
version = "0.1.1"
description = "Retag converted audiobooks (ID3 / filenames) without re-encoding."
authors = ["Brandon Shelley <brandon@pacificaviator.co>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "fixm4b", from = "src" }]
include = [{ path = "src/fixm4b/colors.ini", format = ["sdist", "wheel"] }]

[tool.poetry.dependencies]
python = "^3.12"
mutagen = "^1.47.0"
rapidfuzz = "^3.13.0"
requests = "^2.32.3"
requests-cache = "^1.2.1"
cachetools = "^5.5.2"
pydantic = "^2.11.5"
tinta = "^1.1.0"
regex = "^2024.11.6"
titlecase = "^2.4.1"
goodscraps = "^0.1.4"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
ruff = "^0.11.11"
mypy = "^1.15.0"

[tool.poetry.scripts]
fixm4b = "fixm4b.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra"

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501", "E714", "E402", "E731", "E741"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"src/fixm4b/ol_lookup.py" = ["E741", "F401"]
"src/fixm4b/cli.py" = ["E402", "F401"]
"src/fixm4b/helpers/term.py" = ["E402", "F401"]
"src/fixm4b/metadata/*" = ["F401"]

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
